import Head from 'next/head'

import { Box, Container, Flex, Grid } from '@chakra-ui/react'

import { Header } from '@/components/Header'
import { Introduction } from '@/components/Introduction'
import { Description } from '@/components/Description'
import CardContainer from '@/components/CardContainer'
import ToolsCard from '@/components/ToolsCard'
import ExperienceCard from '@/components/ExperienceCard'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9235619139318053"
        crossorigin="anonymous"></script>
      </Head>

      <Header />
      <main>
        <Container size={{lg: 'lg'}} maxW="800">
          <Introduction />
        </Container>
        <Box backgroundColor='#06dfd5'>
          <Container size={{lg: 'lg'}} maxW="800">
            <Description />
          </Container>
        </Box>
        <Box p={{sm: '15px', lg: '30px'}} as={Grid} templateColumns='repeat(3, 1fr)' gap='20px'>
          <CardContainer />
          <ToolsCard />
          <ExperienceCard />
        </Box>
      </main>
    </>
  )
}
